### ISSUE TITLE
Please add a license and LICENSE file

### ISSUE THREAD

**Issue by jaredsmith** [uNetworking/uSockets#1]
Would you please choose an open source license for this project, and add the text of the license to a LICENSE file?  I'd love to use this package in a project I'm working on, but want to make sure it's available under a common open source license.

**Comment by alexhultman** [comment]
Yep, done. But note that this project is still very broken. It will probably be broken for a while.

µTT and µWS (0.15+) are to use this, but currently no production code runs on it (thankfully). µWS 0.14 still has its own stack.
