### ISSUE TITLE
Node.js support as TCP server?

### ISSUE THREAD

**Issue by dalisoft** [uNetworking/uSockets#103]
Thanks for best things you made.

I use uWebSockets.js and it works fine, but now i want create own "Language Protocol Server", but performance and memory usage of basic node.js TCP (net module) server does not meet requirements for high-performance replies.

It is possible in future release of this library/module for Node.js as TCP server?

**Comment by alexhultman** [comment]
Yes but that's not planned right now

**Comment by dalisoft** [comment]
Thanks, I’ll wait. 
I will be first tester

**Comment by alexhultman** [comment]
This will likely never happen
