### ISSUE TITLE
installation make error

### ISSUE THREAD

**Issue by sas05** [uNetworking/uSockets#106]
platform ubuntu 18.04
after make command I have got this following error.

make -C uSockets; \
for FILE in HelloWorld EchoServer BroadcastingEchoServer UpgradeSync UpgradeAsync; do g++ -flto -O3 -lpthread -Wconversion -std=c++17 -Isrc -IuSockets/src examples/$FILE.cpp -o $FILE uSockets/*.o -lz & done; \
for FILE in HelloWorldThreaded EchoServerThreaded; do g++ -pthread -flto -O3 -lpthread -Wconversion -std=c++17 -Isrc -IuSockets/src examples/$FILE.cpp -o $FILE uSockets/*.o -lz & done; \
wait
make[1]: Entering directory '/home/saeed/workspace/deepstream.io-benchmarks/uWebSockets/uSockets'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/saeed/workspace/deepstream.io-benchmarks/uWebSockets/uSockets'
g++: error: uSockets/*.o: No such file or directory
g++: error: uSockets/*.o: No such file or directory
g++: error: uSockets/*.o: No such file or directory
g++: error: uSockets/*.o: No such file or directory
g++: error: uSockets/*.o: No such file or directory
g++: error: uSockets/*.o: No such file or directory
g++: error: uSockets/*.o: No such file or directory

**Comment by alexhultman** [comment]
I can't see anything from that log? I don't know why you would get that. I need more info

**Comment by alexhultman** [comment]
You didn't clone recursively? I got the same error when I forgot to clone recursively
