### ISSUE TITLE
Discrepancy between uWebSockets and uSockets releases

### ISSUE THREAD

**Issue by epsilon-0** [uNetworking/uSockets#107]
Seems like the latest uWebSockets release (and also the 18.4.0) release is incompatible with uSockets 0.4.0 as they need `us_socket_get_native_handle`.

Simple resolution: make a release for uSockets

Side note: I've been able to get uSockets and uWebSockets as a package into both Gentoo and OpenBSD. Thanks a lot for this work :)

**Comment by alexhultman** [comment]
0.4.1 released

**Comment by epsilon-0** [comment]
Wow, really fast response.  
Thanks a lot!
