### ISSUE TITLE
uv.h is missing

### ISSUE THREAD

**Issue by sadeghitk** [uNetworking/uSockets#113]
Hi,
Compiling under win10, using VS2017. The file "uv.h" is missing. It is refered in "libuv.h",

uSockets-master\src\internal\eventing\libuv.h

Thanks,

**Comment by alexhultman-2fa** [comment]
uv.h is part of libuv you need to link to and include it

**Comment by sadeghitk** [comment]
U mean "https://github.com/libuv/libuv" ?
Thanks,

**Comment by sadeghitk** [comment]
FYI
VS2017 (VS2015 & VS201) with CMake option will create the various lib's. It is very straightforward. 
https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2017
