### ISSUE TITLE
SSL handshake hangs after SSL_ERROR_WANT_WRITE in SSL_read()

### ISSUE THREAD

**Issue by andreysm** [uNetworking/uSockets#127]
In ssl_on_data(), SSL_read() call emits SSL_ERROR_WANT_WRITE during handshake when sending large ceritficate. Since it is a handshake, the app is waiting for read, but openssl needs to be called again to write the rest (waits for a 'writable' event).

I implemented ssl_on_writable() in the same manner as ssl_on_data() in order to retry SSL_read() in state 'ssl_read_wants_write'. It seems to fix the problem. 

Please look at the patch attached:
[want_write.patch.txt](https://github.com/uNetworking/uSockets/files/5310953/want_write.patch.txt)

**Comment by alexhultman** [comment]
Thanks for the explanation. I will look into this. Great find.

**Comment by alexhultman** [comment]
This looks correct - did you have any problem after this? It is kind of a deadlock where the handshake has failed and we don't have anything (in application) to send, so it doesn't progress.

**Comment by andreysm** [comment]
It works well for me.

**Comment by alexhultman** [comment]
I've applied your patch with minor changes (on_writable called after on_read called, comments). Please try v0.7.1
