### ISSUE TITLE
Release v0.6.0 sni_tree.cpp lacks <cstdlib> header file.

### ISSUE THREAD

**Issue by BFamzz** [uNetworking/uSockets#128]
The header file <cstdlib> is not included in the release version v0.6.0. 

I saw a new [commit](https://github.com/uNetworking/uSockets/commit/7dea1e00ae922f3d1bf23d53dedebdf45f21dc3b) fix this issue but was not upgraded to the [current release](https://github.com/uNetworking/uSockets/commit/0a81a97aa2182cbf55a38bc18196ef6c535c3981)

**Comment by alexhultman** [comment]
There will be a new release at some point.
