### ISSUE TITLE
us_loop_free memory corruption / heap error

### ISSUE THREAD

**Issue by xXDangerous** [uNetworking/uSockets#13]
Hello,
I'm using your framework to rewrite an MMORPG back-end. While I do realize that there are still a few tweaks required here and there, I stumbled across the following error:

When using us_loop_free to terminate the default loop (created with us_create_loop(0, ...), an exception is thrown: https://i.gyazo.com/db87de7a1567ff6a3fa60671d83c1bb2.png

This one was triggered by executing my App::shutdown call from within my OnIdle callback (just a timer called every x ms).

The shutdown method simply closes my OnIdle timer and then calls us_loop_free.

I've also implemented a small wrapper for creating signals (just for libuv), which does actually work. However, when calling my shutdown method from within the signal callback (to clean up and do a clean shutdown of the program), I get this error: https://i.gyazo.com/459cc385f6befba569111d1457b5f3b1.png

I've tested any possible scenario, and the only working one where no error is thrown is when I terminate the program with exit() from anywhere (even inside my OnIdle callback) as long as I don't do any us_loop_free calls.

One more test I did was replacing the deprecated uv_loop_delete function with uv_loop_close and manually free'd the loop with uv__free. Also tried removing the uv_run call inside the us_loop_free function. Both tests ended up with the same error as above with the next_idle_handle being invalid.

Any solution for this? I did everything exactly as shown in your examples. 
I'm running this on Windows 10 x64, Visual Studio 2017. Libuv 1.23.2.

**Comment by alexhultman** [comment]
You can only free the loop if us_loop_run has returned (passively)

**Comment by xXDangerous** [comment]
I see.. Indeed, it works now without yelling. Thanks!

Any plans for integrating signal handling in this framework or is it out of scope? I could send you my implementation if desired.

**Comment by alexhultman** [comment]
Signals could come in if they are needed. Currently I only focus on getting µWS out.
