### ISSUE TITLE
Support ephemeral ports

### ISSUE THREAD

**Issue by alastairpatrick** [uNetworking/uSockets#135]
BSD sockets allows the kernel to assign a random port to a listening socket rather than the application. One way to accomplish this, for example, is to pass 0 as the port number to bind().

Ephemeral ports will be a necessary feature for my application so I have implemented uSocket support for them in a fork. Usage is like this:

```
int requested_port = 0;  /* Request an ephemeral port */
struct us_listen_socket_t *listen_socket = us_socket_context_listen(
    SSL,
    http_context,
    0,
    requested_port,
    0,
    sizeof(struct http_socket));

int assigned_port = us_socket_local_port(SSL, (struct us_socket_t*) listen_socket);
printf("Listening on port %d...\n", assigned_port);
```

The new us_socket_local_port() returns the port number regardless of whether zero or a specific port number was passed to us_socket_context_listen().

Pull request incoming.

**Comment by alastairpatrick** [comment]
I implemented my own HTTP server so won't need this feature anymore. I'm willing to work on the patch more with a view to checking it in if of value but won't be troubled at all if you close.

**Comment by alexhultman** [comment]
This is already supported you pass 0 as listen port. What is needed is a function to get whatever the port was chosen.

us_listen_socket_get_port

**Comment by alexhultman** [comment]
PR merged 👍
