### ISSUE TITLE
us_poll_resize is broken and has been for long with libuv

### ISSUE THREAD

**Issue by ludekvodicka** [uNetworking/uSockets#139]
Hi,
I found another problem on Windows 64-bit target (32-bit works ok, and also 64-bit linux works ok).

This issue is probably dependent on PerSocketData struct size and alignment. Here is a minimal test case that completely crashed immediately after disconnection:

	struct PerSocketData
	{
		int64_t id;
		void* ptr;
		std::function<void()> fce;
	};

	uWS::App::WebSocketBehavior behavior;
	behavior.message = [](auto* ws, std::string_view message, uWS::OpCode opCode){};

	uWS::App app;
	app.ws<PerSocketData>("/*", std::move(behavior));
	app.listen(9001, [&](auto* listenSocket) {});
	app.run();

This is asserting window:

![AtomixDevelopment_2020-12-23_14-26-43](https://user-images.githubusercontent.com/3900551/103000231-ece05580-452a-11eb-8744-f3fa9cdf7a9b.png)

and here is callstack:

![devenv_2020-12-23_14-27-15](https://user-images.githubusercontent.com/3900551/103000259-fb2e7180-452a-11eb-990b-1962d7f6612e.png)

and here crashing code:

![devenv_2020-12-23_14-29-05](https://user-images.githubusercontent.com/3900551/103000375-3fba0d00-452b-11eb-9b97-faf0dff2d4ca.png)

It's tested on two clients (IXWebsocket and websocat). Both with the same results.

The issue occurs only on some PerSocketData configurations and only on Win 64-bit target. When any of these three variables are removed, the application works ok.

**Comment by ludekvodicka** [comment]
It's interesting that the bug occurred only on 64-bit windows and on some configurations. But I'm glad you find it.

**Comment by Sunstradamus** [comment]
> Can you provide a case that fails on Linux? I cannot trigger this

The minimal reproduceable case I managed to reconstruct was to build with libuv, accept a websocket connection, send any message to trigger the server to close both the websocket and the listening socket. The destructor will then throw the assertion error when the server gracefully shuts down.

```C++

struct PerWebSocketData {
    //char buffer[512]; doesn't seem to be necessary to trigger the assertion
};

const int listen_port = 9001;
us_listen_socket_t* ws_listener = nullptr;

auto WebSocketServer = uWS::App(ssl_options);
WebSocketServer.ws<PerWebSocketData>("/*", {
    /* Settings */
    .compression = uWS::SHARED_COMPRESSOR,
    .maxPayloadLength = 16 * 1024,
    .idleTimeout = 60,
    .maxBackpressure = 1 * 1024 * 1024,
    /* Handlers */
    .upgrade = nullptr,
    .open = [](auto *ws) {
        PerWebSocketData* data = (PerWebSocketData*) ws->getUserData();
    },
    .message = [](auto *ws, std::string_view message, uWS::OpCode opCode) {
        //ws->send(message, opCode, true);
        if (ws_listener) {
            us_listen_socket_close(0, ws_listener);
            ws->end();
        }
    },
    .drain = [](auto *ws) {
        /* Check ws->getBufferedAmount() here */
        /* Called after some successful send */
    },
    .ping = [](auto *ws) { },
    .pong = [](auto *ws) { },
    .close = [](auto *ws, int code, std::string_view message) {
        PerWebSocketData* data = (PerWebSocketData*) ws->getUserData();
    }
});
WebSocketServer.listen(listen_port, [&ssl_options, hostname, port](auto *socket) {
    if (socket) {
        ws_listener = socket;
        std::cout << "Listening on port " << listen_port << std::endl;
    }
});
WebSocketServer.run();
```

This might be a different issue altogether, but it seems to fit in line with `us_poll_resize`.

**Comment by alexhultman** [comment]
should be fixed now
