### ISSUE TITLE
How to add tty fd to poll?

### ISSUE THREAD

**Issue by d1ken** [uNetworking/uSockets#140]
Hello.

I need to read from serial device, process data and send over http/ws and backwards http > process data > serial device.
Is it possible to work with serial device like with sockets with this lib?
For linux's poll/epoll there are no difference what fd what represent.

**Comment by alexhultman** [comment]
If you compile with libuv you can use uv_poll_t together with the uv_loop_t in any way you want

**Comment by d1ken** [comment]
Yes, there are no problems with libuv.
But what about us_poll_t and us_loop_t?
How to combine them?
Or I should just use separate instances?

**Comment by alexhultman** [comment]
Yes you can poll for whatever FD that way. Look in the libusockets header and you should find your way. Or just compile with libuv as that library is better documented.
