### ISSUE TITLE
uSockets with WolfSSL

### ISSUE THREAD

**Issue by Tobita0815** [uNetworking/uSockets#147]
Hello,

when I want to compile uSockets with WolfSSL(both the latest version today) as lib, I get the following error:

\crypto\wolfssl.c(600,34): error C2040: "us_internal_ssl_socket_close": "us_internal_ssl_socket_t *(us_internal_ssl_socket_t *)" unterscheidet sich von "int ()" in Bezug auf die Anzahl vorgenommener Dereferenzierungen

\crypto\wolfssl.c(602,58): error C2198: "us_socket_close": Nicht genügend Argumente für Aufruf.

Attention, the code file has been formatted and the line number will therefore be different from the original!

What's going wrong there?

**Comment by Tobita0815** [comment]
struct us_internal_ssl_socket_t* us_internal_ssl_socket_close(struct us_internal_ssl_socket_t* s)
{
	return (struct us_internal_ssl_socket_t*)us_socket_close(0, (struct us_socket_t*)s);
}

Here is the error

**Comment by alexhultman** [comment]
#111
