### ISSUE TITLE
clang compilation database

### ISSUE THREAD

**Issue by ramblehead** [uNetworking/uSockets#154]
I have added make ```commands``` .PHONY targets to my forks to output compilation commands to ```commands.log``` files ([uSockets fork](https://github.com/cambustion/external-uSockets/commit/9cc6082024c57529bcb15885bd33b81b23fbb637) and [uWebSockets fork](https://github.com/cambustion/external-uWebSockets/commit/78c0784bc02bbd2ea9066b40169b719b4a608d35)).

```commands.log``` files can then be used with tools such as [commands_to_compilation_database](https://github.com/tee3/commands_to_compilation_database) to generate Subj.

Then can use rtags, clangd etc. nicies on the source code nearly out-of-the-box.

Is there any interest adding ```commands``` targets (or similar) to the upstream?

**Comment by alexhultman-2fa** [comment]
There are a billion different "build systems" and adding all of them is practically impossible. That's why there is only a simple Makefile producing a simple .a static library.
