### ISSUE TITLE
us_timer_set uses wrong timings in 32 bit systems

### ISSUE THREAD

**Issue by SlavSlavov** [uNetworking/uSockets#156]
In 32 bit systems, where `sizeof(long)` is 4, the calculation of nanoseconds may give negative values which makes `timerfd_settime` to fail silently (as the return code is not checked).

This can easily be reproduced by replacing `long` with `int` on 64 bit systems. Here is a [code example](https://wandbox.org/permlink/FPGiVs8MfwFHMicw)

This was discovered on an embedded system with iMX6 and the musl libc toolchain.

**Comment by alexhultman** [comment]
Can you point to where this issue is in the code? Post permalink

**Comment by SlavSlavov** [comment]
Alex, sorry, I was using outdated code and didn't check the latest version. The latest works fine. Here is the old one:
``` C
    struct itimerspec timer_spec = {
        {repeat_ms / 1000, ((long)repeat_ms * 1000000) % 1000000000},
        {ms / 1000, ((long)ms * 1000000) % 1000000000}
    };
```
