### ISSUE TITLE
Support for standalone ASIO

### ISSUE THREAD

**Issue by Lssikkes** [uNetworking/uSockets#161]
I took a stab at porting the new ASIO backend to using the standalone ASIO library, but it was not as trivial as I'd hoped (posix::descriptor not available, nor is the timer, though there's an alternative using std::chrono). Are there any plans for standalone ASIO support?

**Comment by yangxingpping** [comment]
@Lssikkes  I am also want something like this, can you share the code. or something describe in this 
[https://github.com/uNetworking/uSockets/issues/14](url)

**Comment by Lssikkes** [comment]
@yangxingpping Unfortunately haven't tried further, currently just using libuv on windows and the native implementation on linux. Seems to work well enough.

**Comment by alexhultman** [comment]
Asio support is aimed at Boost users and eventually standard C++.
