### ISSUE TITLE
Arbitrary flags to the `send` syscall

### ISSUE THREAD

**Issue by JWalker1995** [uNetworking/uSockets#162]
I noticed that it seems like the length argument in AsyncSocket::write will end up as arbitrary flags in the `send` syscall, unless I'm misunderstanding something:

[AsyncSocket.h#L19](https://github.com/uNetworking/uWebSockets/blob/0ede7e5d8e4c1ff0a0b1c67a36a181ceb3e172a9/src/AsyncSocket.h#L193) -> [socket.c#L150](https://github.com/uNetworking/uSockets/blob/f6b00aa8bf725d372b68c5f8ef9d10cac3610c21/src/socket.c#L150) -> [bsd.c#L190](https://github.com/uNetworking/uSockets/blob/5440dbac79bd76444175b76ee95dfcade12a6aac/src/bsd.c#L190)

**Comment by alexhultman** [comment]
(msg_more != 0) * MSG_MORE should solve it

**Comment by JWalker1995** [comment]
👍 or even just `msg_more ? MSG_MORE : 0`; the multiplication seems a little misplaced

**Comment by AdrianEddy** [comment]
Doesn't the condition introduce branching? `send` seems like a frequently called function and multiplication (given that `msg_more` is guaranteed to be 0 or 1) should be faster than a condition

**Comment by JWalker1995** [comment]
I'd be surprised if it compiles any differently

**Comment by alexhultman** [comment]
msg_more ? MSG_MORE : 0 is ofc the most elegant but what can you do when you haven't slept properly since 2017. It compiles to the same in gcc and clang
