### ISSUE TITLE
Ability to get remote port

### ISSUE THREAD

**Issue by elan** [uNetworking/uSockets#169]
Is there a reason there's no `us_socket_remote_port` to sit alongside `us_socket_remote_address`? Perhaps I'm missing something and there's another way to obtain that data.

**Comment by alexhultman** [comment]
us_socket_remote_address is there so adding us_socket_remote_port is welcome. Nobody has requested such a function before. You want to know the ephemeral port?

**Comment by elan** [comment]
yeah, just to be able to key a remote connection based on remote address and port, e.g.

**Comment by alexhultman** [comment]
us_socket_local_port and us_socket_remote_address should be replaced with functions that return both IP and port in one go.

us_socket_local_address and us_socket_remote_address are better names

**Comment by Jacob-Burckhardt** [comment]
> Is there a reason there's no us_socket_remote_port

I added it in [PR](https://github.com/uNetworking/uSockets/pull/210).
