### ISSUE TITLE
Broken SSL build

### ISSUE THREAD

**Issue by mumbleskates** [uNetworking/uSockets#173]
https://github.com/uNetworking/uSockets/pull/171 breaks the build with openssl/boringssl enabled, because there is no such member `ssl_ciphers` in type `struct us_socket_context_options_t`.

**Comment by mumbleskates** [comment]
It kind of seems like several places were changed to assume this field's presence, including libuwebsockets' `App.h`, but it doesn't seem to have been actually added to `libusockets.h`.

**Comment by shaharmor** [comment]
Thanks, I'm creating a PR to fix this

**Comment by mumbleskates** [comment]
@shaharmor This change should also be merged into https://github.com/uNetworking/uWebSockets/blob/44af0e571031d9ff9ced76e6b9dbe921ec4aa247/src/App.h#L72-L89 so the usockets dependency can be upgraded.

**Comment by shaharmor** [comment]
@mumbleskates There's already a PR for that here: https://github.com/uNetworking/uWebSockets/pull/1449

**Comment by mumbleskates** [comment]
@shaharmor aha, thanks
