### ISSUE TITLE
Build steps

### ISSUE THREAD

**Issue by websocket98765** [uNetworking/uSockets#18]
uWebsockets can be built using:
```
make 
sudo make install
```
and included with
```
#include <uWS/uWS.h>
```

But uSockets doesn't have the same steps & the Makefile only builds demo applications. Can you provide guidance on to build/install uSockets so that it can be used in a user application via `#include <libusockets.h>` please? 

I can submit your response as a PR to update the README. Thanks.

Edit: Goal is to use with a C++ project also containing uWebsockets.

**Comment by alexhultman** [comment]
I don't get it. The project already has a Makefile very clearly showing how you can build it. It's C - you shove those C files to your C compiler. That's about it.

**Comment by websocket98765** [comment]
I thought it could be installed on the target machine and then used in the C++ app by using a link flag, like uWebsockets (`-uWS`). But I understand now the uSockets C files need to be compiled with a C compiler, the c++ files with a C++ compiler, and then all linked together using a C++ compiler. Will try to get that working.

(Writing to help future searchers.)
