### ISSUE TITLE
Only up to 1017 tcp clients are accepted when using epoll

### ISSUE THREAD

**Issue by renzibei** [uNetworking/uSockets#190]
When I test the echo server with multiple clients, I found some problems about the maximum number of clients when use epoll. I create about 16384 clients and the test goes well with normal epoll echo server (without using uSockets). But when I use uSockets, the number of accepted clients are no more than 1017 and then the other unaccepted clients will start to get RST messages from server. 

Is there a limit on the maximum number of clients or is there possible starvation for accepting? I have raised the limit of maximum number of fds in Linux.

**Comment by uNetworkingAB** [comment]
There is no difference from "a normal epoll server" and uSockets. Both can easily get 1 million connections without any issue if you configure your Linux system as needed. There are tons of generic tutorials on this subject and so this is not a bug that needs tracking here.

**Comment by renzibei** [comment]
But I do observe this happening. This at least suggests some sort of starvation, where some connections are prioritized while others are not immediately accepted. Currently my tests mainly use short tcp connections.

**Comment by uNetworkingAB** [comment]
So, this is not an argument - this is me telling you how it is. You need to direct your generic networking questions to someone who is willing to guide you, or take the time to do your own research. I know from objective reality that the problem you describe is not a problem with the software, it is a Linux config issue and I have, not one second of time, to convince you.
