### ISSUE TITLE
Comparison of TCP implementation to @alexhultman/tcp project?

### ISSUE THREAD

**Issue by brodybits** [uNetworking/uSockets#2]
I noticed that both <https://github.com/alexhultman/tcp> and this project offer some kind of an experimental user-space TCP implementation. I gather that this project offers TCP with Berkeley sockets and Epoll (user-space TCP with Berkeley sockets and epoll?) while <https://github.com/alexhultman/tcp> does not include either one. Can you explain this further?

I completely understand that both projects are marked "experimental" but am sure we can learn a lot from what is already there.

**Comment by alexhultman** [comment]
"tcp" is an experimentation of parts of uSockets.
