### ISSUE TITLE
Compile static library on windows

### ISSUE THREAD

**Issue by 0xMemoryGrinder** [uNetworking/uSockets#203]
Hello,

Since the symbols exports were removed in #184, I'm wondering how I can compile uSockets on windows and get aml the symbols when I link it to a shared library.

Since the macro is not applied anymore to all the functions, when compiling on windows (and macos btw), the symbols are not exported and the linking step of my shared library fails.

How can I solve that ? 

Thanks in advance

**Comment by glingy** [comment]
As mentioned in the PR you linked, this should really not be used as a shared library. The performance as a shared library is far worse than as a static library with LTO enabled. It was decided in that PR that support for shared libraries was not worth cluttering the output of statically built executables with extra exported symbols.

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/uSockets/releases/tag/v0.8.5
