### ISSUE TITLE
Bind Socket to a Logical Core

### ISSUE THREAD

**Issue by victorstewart** [uNetworking/uSockets#23]
this might be of some fun for you

![image](https://user-images.githubusercontent.com/17534897/50021707-eddb6580-ffa7-11e8-8be0-91eff32d703c.png)

**Comment by alexhultman** [comment]
Oooh!

This is new right? REUSEPORT was added in Linux 3 something but back then it only did round-robin accept right? So this is some kind of function you distribute accepts with?

**Comment by alexhultman** [comment]
http://man7.org/linux/man-pages/man7/socket.7.html

Seems new to Linux 4.6

**Comment by victorstewart** [comment]
check this out too. I've been itching to blow out the network stack and replace it in userspace for the past year (nothing worse than decrepit old junk getting in the way).

https://dpdksummit.com/Archive/pdf/2016Asia/DPDK-ChinaAsiaPacificSummit2016-Park-FastUser.pdf

These are the two top implementations:

https://github.com/mtcp-stack/mtcp
https://github.com/F-Stack/f-stack

The only trick is if you sever the NIC from the kernel, it suffocates all networking ability from the OS. (My application servers only run a single application server tho.... so isn't much of a problem for me). So any other running network applications would need to be routed through the new userspace networking stack.

This will only become even more needed with... 60 physical core systems running 40Gb connects soon.

**Comment by alexhultman** [comment]
Yes one of the main ideas of uSockets is to be compatible with mtcp and such stacks. However, one have to take into account the money flow -> Node.js is MASSIVELY popular and Node.js is never going to use mtcp or things like that. So it kind of won't pay off.

I'm scrolling through the Linux kernel more lately though... 10 years from now I will be a Linux kernel dev for sure *fingers crossed*.

**Comment by alexhultman** [comment]
#17
