### ISSUE TITLE
Segmentation faul in destruction of application

### ISSUE THREAD

**Issue by maldag** [uNetworking/uSockets#233]
Referring to https://github.com/uNetworking/uWebSockets/issues/1816 I did some more tracing and this code will cause a segmentation fault if `context->prev` is NULL. 
Please add a check as done for `context->next`.

```
if(context->prev)
  context->prev->next = context->next;
```

https://github.com/uNetworking/uSockets/blob/55e7123d02cc302401a2ce8ac1d0854521761983/src/loop.c#L77

**Comment by uNetworkingAB** [comment]
It could be an issue with having many Apps (contexts).

**Comment by maldag** [comment]
it is just a bug not checking the pointer before dereferencing it. In all other cases context->prev is checked before using it, here it is not.

**Comment by uNetworkingAB** [comment]
No. context->prev is only NULL if context is the head of the list.

**Comment by uNetworkingAB** [comment]
Did you even manage to produce a reproducing snippet of code? Because every time you post these self assured posts about things being wrong, yet, the analysis shows you're wrong, you fall in credibility. Like when you posted self assured opinions about the use of deleted pointer I had to tell you MANY times how you were wrong. Likewise here, I spend time looking for ghosts under the bed because you say there are ghosts. Yet, you can't show a reproducer.

Merit is dwindling.

**Comment by maldag** [comment]
Well, your library code is not easy to integrate so I used conan to do so. I'm still writing tests as seen in the other issue in uWebsockets. If the uWS::App is destructed and no `run()` method is called, you will get this error, even when you close the listening socket as you pointed out in the other issue. 
I did follow the rules to open and close it. IMHO it is just not well documented on how to really adopt your library. So I was following the examples in uWebSocket and you're not testing your example code.

Other than that I don't really see a problem in including and `if()` block for this case. It might seem a rare case, but it is definitely there.

**Comment by uNetworkingAB** [comment]
And here we go again. The arguments and repetition of already disproven facts. Just like when you argued for 10 messages about something you ultimately had misunderstood.

You literally clone the repo, and hit "make". It can't be any easier. And I already tested those cases that you vehemently claim reproduces the problem. It doesn't. I already tested all cases you have mentioned.

Congratulations; you are now lowest credibility user and I will ignore all issues you post until you can logically and irrefutably reproduce your issue.
