### ISSUE TITLE
on_open error handling

### ISSUE THREAD

**Issue by ddosoff** [uNetworking/uSockets#24]
How I can detect connect errors?

**Comment by alexhultman** [comment]
Read the docs and don't open bug reports to get free support

**Comment by ddosoff** [comment]
Hello Alex.

If you want to monetize support, make clear the price for individuals like
me. I'm not bitfinex.

It seems error handling absent for client sockets. Why not to pass error
from poll?

**Comment by alexhultman** [comment]
Unless something is wrong you should get on close event before on open. That could be improved but works as is

**Comment by ddosoff** [comment]
I'm going to implement async https://tarantool.org/ client using
uWebSockets. Will be great to print connection error, if server port is not
open or some misconfiguration in the server url.

I tried connecting to the closed port. I got on_open, then on_close. When I
uncomented
https://github.com/uNetworking/uSockets/blob/master/src/loop.c#L132 I see
socket error 24.

Why not to pass it to on_open?

**Comment by ddosoff** [comment]
You can get error from async socket like this:

int valopt;
socklen_t lon;
getsockopt(us_poll_fd(p), SOL_SOCKET, SO_ERROR, (void*)(&valopt), &lon);

if (valopt) {
  fprintf(stderr, "Error in connection() %d - %s\n", valopt,
strerror(valopt));
  exit(0);
}
