### ISSUE TITLE
Termination when using us_loop_integrate()

### ISSUE THREAD

**Issue by abrownsword** [uNetworking/uSockets#33]
I'm using the us_loop_integrate() function to use uWS with my own event loop, but during the exit sequence us_loop_free() calls uv_run().  This is a surprising behaviour -- should we really be re-running the event loop during exit (when stuff has already largely been torn down), especially if its not your own event loop?

**Comment by alexhultman** [comment]
This should be solved now - if you create a loop with default hint then freeing it will not run or delete it, that becomes your problem.

You also don't need to call integrate
