### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [uNetworking/uSockets#44]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [us_create_loop](https://github.com/uNetworking/uSockets/blob/a83f8423af5b4ae088ddb2996a115bab895dd4c3/src/eventing/libuv.c#L117)
- [OPENSSL_init_ssl](https://www.openssl.org/docs/man1.1.1/man3/OPENSSL_init_ssl.html "OpenSSL initialisation") ⇒ [us_internal_init_loop_ssl_data](https://github.com/uNetworking/uSockets/blob/5a4570eac1a699abe8b842972b1a807da8c40abe/src/ssl.c#L285)

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by alexhultman** [comment]
I genuinely want to know - are you autistic? Asperger's? If you are, I can understand and work with you. I know how Asperger affects people. I'm color blind myself - you're socially "color blind". Hard to read nuances of social behavior.

I misjudge traffic lights a lot, you misjudge social queues.

I'm right, am I?
