### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [uNetworking/uSockets#45]
Would you like to [replace any double quotes](https://github.com/uNetworking/uSockets/blob/62ae53c1e91b9511645e3a9139520569e43b81c3/src/libusockets.h#L60 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by alexhultman** [comment]
....I remember you now!

You're that autistic kid whom I blocked in previous organizations for sending me these pointless and passively aggressive hints.

I was going to answer them, but then it clicked - you're that very guy. You were blocked for what? Two years? Then you realize the block did not carry over when the organization changed so here you are again, two years later doing the same very thing. Not changed, not learnt anything.

People don't like you:

https://lkml.org/lkml/2017/10/23/219

I don't like you. You have no social skills.

**Comment by elfring** [comment]
It can occasionally be challenging to achieve agreements on change possibilities around such software implementation details.

**Comment by alexhultman** [comment]
It's not hard to agree at all. I decide. My decision is final.
