### ISSUE TITLE
Build on osx.

### ISSUE THREAD

**Issue by afterlifenirvana** [uNetworking/uSockets#47]
doing make gives me this result 

1 error generated.
In file included from src/socket.c:19:
In file included from src/internal/common.h:24:
src/internal/eventing/epoll.h:23:10: fatal error: 'sys/epoll.h' file not found
#include <sys/epoll.h>
         ^~~~~~~~~~~~~
1 error generated.
In file included from src/eventing/epoll.c:19:
In file included from src/internal/common.h:24:
src/internal/eventing/epoll.h:23:10: fatal error: 'sys/epoll.h' file not found
#include <sys/epoll.h>
         ^~~~~~~~~~~~~
1 error generated.
In file included from src/eventing/libuv.c:19:
In file included from src/internal/common.h:24:
src/internal/eventing/epoll.h:23:10: fatal error: 'sys/epoll.h' file not found
#include <sys/epoll.h>
         ^~~~~~~~~~~~~
1 error generated.
examples/http_server.c:111:51: warning: incompatible pointer types passing 'struct us_new_socket_t
      *(struct us_new_socket_t *, int)' to parameter of type 'struct us_new_socket_t *(*)(struct
      us_new_socket_t *, int, char *, int)' [-Wincompatible-pointer-types]
        us_new_socket_context_on_open(SSL, http_context, on_http_socket_open);
                                                         ^~~~~~~~~~~~~~~~~~~
src/libusockets_new.h:168:126: note: passing argument to parameter 'on_open' here
  ...int ssl, struct us_new_socket_context_t *c, struct us_new_socket_t *(*on_open)(struct us_new_...
                                                                           ^
1 warning generated.
make: *** [default] Error 1

**Comment by afterlifenirvana** [comment]
sys/epoll.h is not supported on osx.

**Comment by alexhultman** [comment]
LIBUS_USE_LIBUV
