### ISSUE TITLE
Not require calling us_loop_run

### ISSUE THREAD

**Issue by abrownsword** [uNetworking/uSockets#6]
Hi Alex,

I'm not using your library yet, but am looking forward to v0.15 as it looks like just what I need.  I was looking through the uSockets code at how you were doing the libuv integration (my app is heavily libuv-based for other tasks, but I want to use your library to add a bit of http serving), and I notice that you provide your own run method:  us_loop_run().  Could I request that use of that method be optional, as other code I have wants to 'own' the call to uv_run?

From what I can see by quick inspection, us_run_loop() just calls us_timer_set() with some internal values and then calls uv_run().  If you could provide something like a us_loop_setup_run() as a wrapper around that us_timer_set() call and is to be called prior to uv_run(), then users who are directly using libuv can use that instead of us_loop_run().

**Comment by alexhultman** [comment]
I need this feature myself. You want to integrate with a default loop. Something like us_loop_run_passively or based on the given default_hint.

**Comment by alexhultman** [comment]
You have us_loop_integrate now that is all you need to integrate with an existing loop

**Comment by abrownsword** [comment]
This works when using the default libuv loop (which I am), but if I were using a uv_loop I created myself I would have no way to pass it through into uSocket's us_loop.

Also, and this is a stylistic point, you don't provide a way to convert between uWS::Loop and us_loop.  This puts an ugly implementation detail into the user's code, so it would be nice to either have a us_loop_integrate wrapper in uWS::Loop or provide a method that does the typecast for the user (in case you ever decide to change your implementation decision).

I am actively integrating uWS/uS into my application, by the way, and have served up my first webpage from it.  I have a pretty trivial use case though, so nothing too exciting but _way_ lighter than my previous solution.

**Comment by alexhultman** [comment]
I'm sure that can be iterated on over time
