### ISSUE TITLE
us_socket_ext confusion

### ISSUE THREAD

**Issue by JadeVand** [uNetworking/uSockets#65]
Hello,
I'm slightly confused about what `us_socket_ext` is doing. Is it allocating memory internally for the size relative to the context structure and returning the newly allocated pointer? Because what I'd like to do is store the socket objects in a class object, but I'd like us_socket_t to be able to reference that object later on. Like a `->data` field. Does `us_socket_t` have a data field I can use or something to reference its parent object. Is `us_socket_ext` meant to return the class object pointer which `us_socket_t` is supposed to be stored in?

**Comment by alexhultman** [comment]
us_whatever_ext returns the extension of whatever. All constructors take ext_size, so if you do not wish to store all of your extension directly along the rest of whatever, you give it size of(void *) for ext_size and interpret us_whatever_ext as void *.

**Comment by alexhultman** [comment]
Extension in this context means user data

**Comment by JadeVand** [comment]
What Is the difference here between

 ```
/* Our socket extension */
struct echo_socket {
    char *backpressure;
    int length;
}; 
```
and 
```
/* Our socket context extension */
struct echo_context {
    
};
``` 

When `on_echo_socket_open` is received, I assume the `us_socket_t` argumentt holds the socket object. But then it gets cast to 
```
struct echo_socket *es = (struct echo_socket *) us_socket_ext(SSL, s);
```
instead of `struct echo_context` even though in main when when `us_socket_context_on_open` was called `echo_context` was passed as the argument and in `us_create_socket_context` the `sizeof(struct echo_context)` was passed. That's mainly where my confusion is.
