### ISSUE TITLE
onopen not receiving ip argument

### ISSUE THREAD

**Issue by JadeVand** [uNetworking/uSockets#69]
In the onopen callback, the ip length shows a value but the char* ip is just an empty string. 
```
struct us_socket_t *onopen(struct us_socket_t *s, int is_client, char *ip, int ip_length) {
    printf("\nconnected:%s %i\n",ip,ip_length);
    return s;
}
``` 
Unless the ip is supposed to be a sock_addr struct?

**Comment by alexhultman** [comment]
Please don't open GitHub issues for support, you'll have to figure things out by yourself
