### ISSUE TITLE
About hub.connect on windows run as blocking mode on uWebSocket

### ISSUE THREAD

**Issue by Furujiang** [uNetworking/uSockets#7]
Hi I could not find a place to quest under uWebsocket, so I post it here:
On winodws 10, while calling hub.connect to wws, it will block several seconds.
if I add predefine SOCK_CLOEXEC;SOCK_NONBLOCK; to project, error occured with identifier "accept4" not found error.

I am using the hub to connect to multi wws, so I need this "connect" function excute as nonblocking, could you please advice? 
thank you!

**Comment by alexhultman** [comment]
It blocks on DNS lookup, that's the only thing blocking. It's a valid issue for uSockets too, I haven't solved it yet. DNS lookup should happen in a thread pool.

**Comment by Furujiang** [comment]
Thank you for quick response, I changed my design to use uws in multithread because I found it don't work for creating multi group and make connect calls, only last connect call works.
It works well in each thread for 1 hub. Thank you again!

**Comment by alexhultman** [comment]
You shouldn't hack with threading. If you require nonblocking DNS lookup then do that part yourself with a third party library and pass the IP to connect

**Comment by Furujiang** [comment]
the main problem for single thread is: below code only connect to url2 will work fine, no callback recieved from url1, is this a bug? thank you!

sample code:
hub_ = new Hub();
group1 = hub_->createGroup<CLIENT>();
group1->onConnection([&](WebSocket<CLIENT> *ws, HttpRequest req) {xxx});
group1->onError([&](void * self) {xxx};
group1->onDisconnection([&](WebSocket<CLIENT> *ws, int code, char *data, size_t length) {xxx});
hub_->connect(url_1, nullptr, {}, 5000, group1);

group2 = hub_->createGroup<CLIENT>();
group2->onConnection([&](WebSocket<CLIENT> *ws, HttpRequest req) {xxx});
group2->onError([&](void * self) {xxx};
group2->onDisconnection([&](WebSocket<CLIENT> *ws, int code, char *data, size_t length) {xxx});
hub_->connect(url_2, nullptr, {}, 5000, group2);
hub->run();

**Comment by alexhultman** [comment]
Well since the first connection will block on DNS resolution the second connection might time out? Both should work.
