### ISSUE TITLE
Multithreading in Windows

### ISSUE THREAD

**Issue by MarouaneMan** [uNetworking/uSockets#74]
Hello,

First of all, thank you for this work, I gave it a test and it's blazing fast.
I just have a little problem, the current proposed multithreading solution has no effect on Windows because SO_REUSEPORT is not supported and does anything, so only one thread will get connections.
Is there anyway to implement multithreading in the listener?

Thank you.

**Comment by xingyun86** [comment]
Why I test it on Linux, but only one thread get the connect.Others wait along???

**Comment by alexhultman** [comment]
I've tested this on windows and it does accept connections on all threads. You don't get any particular guarantee but that's what happens if you load the system

**Comment by alexhultman** [comment]
I can't do anything about this report
