### ISSUE TITLE
Crash with shared_ptr object in ech_socket structure

### ISSUE THREAD

**Issue by Merethiel** [uNetworking/uSockets#76]
Not sure if this is a bug or I was doing something wrong but when trying to create a new shared_ptr object and assigning it to the echo_socket struct member, the server crashes.
The class looks like this
```
class Client : public std::enable_shared_from_this<Client>{
public:
    char *backpressure;
    int length;     
    bool alive;
    Client(){
        alive = false;
        backpressure = nullptr;
        length = 0;


        std::cout << "shared client allocated" << std::endl;
    }
    ~Client(){
        std::cout << "shared client destroyed" << std::endl;
    }
};
``` 
The echo_socket looks as such
```
/* Our socket extension */
struct echo_socket {
    std::shared_ptr<Client> c;
};
```

The socket context is created with sizeof(echo_socket)
```
struct us_listen_socket_t *listen_socket = us_socket_context_listen(SSL, echo_context, 0, 8070, 0, sizeof(struct echo_socket));
```
and in the on_echo_socket_open callback the object is created and assigned
```
/* Socket opened handler */
struct us_socket_t *on_echo_socket_open(struct us_socket_t *s, int is_client, char *ip, int ip_length) {
    struct echo_socket *es = (struct echo_socket *) us_socket_ext(SSL, s);
    
    /* Initialize the new socket's extension */
    std::shared_ptr<Client> c(new Client());
    es->c = c;
    es->c->backpressure = 0;
    es->c->length = 0;
    
    /* Start a timeout to close the socekt if boring */
    //us_socket_timeout(SSL, s, 30);
    
    printf("Client connected\n");
    
    return s;
}
```
but this line is where the crash occurs
```
es->c = c;
```   
Do you know why this might be happening?
Strange this is...it doesn't always crash but like 1/3 times
the location of the crash leads to this code in c++ memory header
```
template <class _Tp>
inline _LIBCPP_INLINE_VISIBILITY _Tp
__libcpp_atomic_refcount_decrement(_Tp& __t) _NOEXCEPT
{
#if defined(_LIBCPP_HAS_BUILTIN_ATOMIC_SUPPORT) && !defined(_LIBCPP_HAS_NO_THREADS)
    return __atomic_add_fetch(&__t, -1, __ATOMIC_ACQ_REL);
#else
    return __t -= 1;
#endif
}
``` 
specifically 
```
return __atomic_add_fetch(&__t, -1, __ATOMIC_ACQ_REL);
```

**Comment by alexhultman** [comment]
You never initialized your shared ptr, it starts with garbage memory. You need to in-place new it.

**Comment by alexhultman** [comment]
Placement new is the name just remembered

**Comment by Merethiel** [comment]
> You never initialized your shared ptr, it starts with garbage memory. You need to in-place new it.

Oh do I have to allocate with new then called make_shared?

**Comment by alexhultman** [comment]
Placement new, look it up

**Comment by Merethiel** [comment]
I'm slightly confused so I tried this
```
     Client* c = new Client();
    es->c = std::shared_ptr<Client>(c);
``` 
And this
```
es->c = std::make_shared<Client>();
```
But still no success

**Comment by alexhultman** [comment]
You need to bring up Google, make a cup of coffee and type in "placement new". This is not a bug, so stop posting here I already pointed out exactly what you need to read up on.

**Comment by Merethiel** [comment]
Sure thing ^^ ☕️🕵️‍♂️
