### ISSUE TITLE
ca/ca_bundle/ca_certificates/trust_bundle option not available in us_socket_context_options_t

### ISSUE THREAD

**Issue by matt-deboer** [uNetworking/uSockets#77]
This could be my own misunderstanding of the protocol (and/or codebase), but I don't see any calls to `SSL_CTX_load_verify_locations` or `SSL_CTX_*_client_CA*` in `ssl.h`; how is the client verification performed? Or are we just getting the `SSL_VERIFY_NONE` behavior by default?

If so, it would be useful to be able to configure a self-generated ca bundle for cert verification...

**Comment by alexhultman** [comment]
Yes client connect is not super prioritized, in worst case you have to grab the context and do it yourself. It should be wrapped up though, people have asked many times

**Comment by matt-deboer** [comment]
Ok, I took a stab at it in #78; PTAL...

**Comment by alexhultman** [comment]
I think it looks very well done
