### ISSUE TITLE
where is the definition of struct us_timer_t?

### ISSUE THREAD

**Issue by uniqss** [uNetworking/uSockets#82]
I greped all the source code but there is no definition of [struct us_timer_t]. So where can I find it?

**Comment by uniqss** [comment]
I can't find the struct us_internal_async either.

**Comment by alexhultman-2fa** [comment]
us_timer_t is actually an us_internal_cb_t or something like that

**Comment by uniqss** [comment]
a typedef？or a #define？
so where is the define？

**Comment by alexhultman-2fa** [comment]
us_timer_t is an opaque (not defined) pointer to us_internal_cb_t or something like that. It's the same as a void pointer, conceptually.

**Comment by uniqss** [comment]
Thanks for your kindly quick answer, but if no typedef and no #define, the us_timer_t will pron a compile-time error. I searched libuv, also not find. Can gcc or g++ accept a not defined type just using pointer? I will have a try.

**Comment by alexhultman-2fa** [comment]
Yes that is a well known design pattern.

**Comment by uniqss** [comment]
Oh, that's awesome!
`192	struct us_timer_t *us_create_timer(struct us_loop_t *loop, int fallthrough, unsigned int ext_size) {
193	    struct us_internal_callback_t *cb = malloc(sizeof(struct us_internal_callback_t) + sizeof(uv_timer_t) + ext_size);
194	
195	    cb->loop = loop;
196	    cb->cb_expects_the_loop = 0;
197	
(gdb) l
198	    uv_timer_t *uv_timer = (uv_timer_t *) (cb + 1);
199	    uv_timer_init(loop->uv_loop, uv_timer);
200	    uv_timer->data = cb;
201	
202	    if (fallthrough) {
203	        uv_unref((uv_handle_t *) uv_timer);
204	    }
205	
206	    return (struct us_timer_t *) cb;
207	}
`
I am just wondering how to get the [ext]. uv_timer_t *uv_timer = (uv_timer_t *) (cb + 1); just get the uv_timer_t, but how to get the ext? first trans cb + 1 to uv_timer_t and the +1 again?
