### ISSUE TITLE
Loading certificates from memory

### ISSUE THREAD

**Issue by fhajji** [uNetworking/uSockets#85]
Hello,

when running in a Consul cluster, one gets the CA root certificate, client certificates and private keys directly from the network, i.e. from the local consul Agent using a RESTful API. Those certificates are short-lived and highly dynamic, because that service mesh rotates them frequently:

https://www.consul.io/docs/connect/native.html
https://www.consul.io/api/agent/connect.html#certificate-authority-ca-roots
https://www.consul.io/api/agent/connect.html#service-leaf-certificate

In other words, no files are involved. All key material stays in memory, where it belongs, and doesn't touch the file system / disks.

Unfortunately, in uWS::SSLApp(), one can only pass those certificates and keys as paths to files (.key_file_name, .cert_file_name, .ca_file_name), as specified in uSockets' us_create_socket_context().

So right now, I need to frequently write that key material I get from Consul into various files, which is quite unfortunate. It would be much better to be able to pass those values as strings to uWS::SSLApp() constructor as additional options as well.

Thanks.

Edit: Here's [one way to do it](https://stackoverflow.com/a/3812457/12720557) with OpenSSL, but it is limited to RSA keys. I'm getting EC keys from Consul...

**Comment by fhajji** [comment]
Thanks, I know that, and that's precisely what I am doing right now. The problem with that is when multiple processes are running on the same machine under the same user account, as happens in many micro service architectures. All those processes can access that key material, even though they are not supposed to trust each others. Setting up different users may be possible, e.g. in EC2, but in Docker environments, especially in managed architectures, that is an entirely different matter.

**Comment by alexhultman** [comment]
You should be able to cook something up with the added us_socket_context_get_native_handle that returns the SSL_CTX.
