### ISSUE TITLE
bsd_create_connect_socket uses synchronous getaddrinfo

### ISSUE THREAD

**Issue by andreysm** [uNetworking/uSockets#89]
Maybe it is better to use uv_getaddrinfo (in libuv case) to make it more asynchronous?
If other event libraries doesn't have similar option, they can fallback to getaddrinfo_a (GNU glibc specific) or to synchronous getaddrinfo. At least, it can be made asynchronous for libuv.

**Comment by alexhultman-2fa** [comment]
Yep this should be fixed but I dns lookup is not part of the eventing layer, so cannot use libuv (it is only used for eventing)
