### ISSUE TITLE
Windows MSVC C++ build - redefinition of keyword alignas

### ISSUE THREAD

**Issue by connorjak** [uNetworking/uSockets#90]
I installed uSockets through vcpkg, and got `usockets:x64-windows 0.3.5-1`. In a CMake project built with ninja/MSVC, I get an error for this library redefining `alignas`. This does not change if I change the C++ standard to cpp11, 14, or 17. I am in the process of porting from Linux to Windows, so my build configuration is not exactly the most stable, but currently this is my only error. What is your best guess for what can fix this? It might have to do with a check for if alignas is already defined.

Lines 30-41 on libusockets.h:
```
/* Define what a socket descriptor is based on platform */
#ifdef _WIN32
#define NOMINMAX
#include <WinSock2.h>
#define LIBUS_SOCKET_DESCRIPTOR SOCKET
#define WIN32_EXPORT __declspec(dllexport)
#define alignas(x) __declspec(align(x)) //<---------------
#else
#include <stdalign.h>
#define LIBUS_SOCKET_DESCRIPTOR int
#define WIN32_EXPORT
#endif
```

Output Log:
```
>------ Build All started: Project: linux_SystemManager, Configuration: x64-Debug ------
  [1/2] C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\HostX64\x64\cl.exe  /nologo /TP  -IC:\Users\Me\Documents\GitHub\vcpkg\installed\x64-windows\include -I..\..\..\server -I..\..\..\externals /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1   /W3 -std:c++14 /showIncludes /FoCMakeFiles\run_Server.dir\server\main.cpp.obj /FdCMakeFiles\run_Server.dir\ /FS -c ..\..\..\server\main.cpp
  FAILED: CMakeFiles/run_Server.dir/server/main.cpp.obj 
  C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\HostX64\x64\cl.exe  /nologo /TP  -IC:\Users\Me\Documents\GitHub\vcpkg\installed\x64-windows\include -I..\..\..\server -I..\..\..\externals /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1   /W3 -std:c++14 /showIncludes /FoCMakeFiles\run_Server.dir\server\main.cpp.obj /FdCMakeFiles\run_Server.dir\ /FS -c ..\..\..\server\main.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xkeycheck.h(26): warning C4005: 'alignas': macro redefinition
  C:\Users\Me\Documents\GitHub\vcpkg\installed\x64-windows\include\libusockets.h(36): note: see previous definition of 'alignas'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xkeycheck.h(28): fatal error C1189: #error:  The C++ Standard Library forbids macroizing the keyword "alignas". Enable warning C4005 to find the forbidden define.
  ninja: build stopped: subcommand failed.

Build All failed.
```

**Comment by connorjak** [comment]
Also, I'm not quite sure if this is the library for me due to some changes required in my architecture to support the async callbacks instead of unix socket calls. Are there any alternative libraries that are cross platform (Windows and Linux) that you can recommend?

**Comment by connorjak** [comment]
There is a way to resolve this by turning off the check here: https://social.msdn.microsoft.com/Forums/vstudio/en-US/6cb13b36-1da5-49ec-895c-e002dfb7546a/xkeycheckh-and-macro-defined-keywords?forum=vcgeneral, but this isn't the best solution.

**Comment by alexhultman-2fa** [comment]
What is your msvc version? It must be new?

**Comment by connorjak** [comment]
MSVC++ 14.24

**Comment by connorjak** [comment]
Or it might have been 14.25 (VS 16.5.x). I think I was on a different computer at the time.

**Comment by alexhultman** [comment]
Okay so you are on the very latest or close to very latest. As soon as that version gets more mainstream, we can just drop this define - it was put in because my msvc didn't support it

**Comment by connorjak** [comment]
For a back-portable solution, you can do 
```
#if _MSC_VER < 1424
#define anignas ...
#endif
```
with whatever MSVC version added the alignas keyword. https://dev.to/yumetodo/list-of-mscver-and-mscfullver-8nd

**Comment by alexhultman** [comment]
I have

Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28614 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

and it still compiles without problem? What flags (if any) enable alignas?

**Comment by alexhultman** [comment]
Ah, I never include stdalign.h for windows

**Comment by jagerman** [comment]
I think #115 will solve this - the alignas macro doesn't need to be in the public header at all (and indeed seems problematic for C++ code that includes the public header).

**Comment by connorjak** [comment]
I am no longer using uSockets, so if the alignas header was removed, this issue can probably be closed.
