### ISSUE TITLE
Please build a shared library instread of, or along with a static library

### ISSUE THREAD

**Issue by yurivict** [uNetworking/uSockets#94]
Shared libraries are better for packaging so that potential issues can be corrected in one place instead of in many places.

Please also add a SONAME for the shared library, for example:
```
libusockets.so.1.0 (file)
libusockets.so -> libusockets.so.1.0 (link)
libusockets.so.1 -> libusockets.so.1.0 (link)
```

This is needed to determine if dependent packages need to be updated when your library changes. The API/ABI breaking changes should trigger the major number bump. Minor changes would only trigger a minor number bump.

**Comment by alexhultman-2fa** [comment]
Shared library would perform very poor since there are very central functions like us_socket_ext which absolutely has to be statically and link time optimized away. These functions are so slim the overhead of having them be dynamical calls would be detrimental.
