### ISSUE TITLE
Standards compliant intallation target

### ISSUE THREAD

**Issue by epsilon-0** [uNetworking/uSockets#98]
I'm trying to make this available as a package on Gentoo linux and was wondering if it is possible to add a small installation target in the Makefile to make it easier to port.

Thanks a lot for the awesome library :)

**Comment by epsilon-0** [comment]
I'm dumb, was a misclick.

**Comment by alexhultman** [comment]
Sorry I have forgotten about this. We added install for uWebSockets but not for uSockets.

Like said, it should install the static library and the public header file, nothing else. I do not want to support shared libraries, as they are way slower for this library.

**Comment by epsilon-0** [comment]
Thats ok. Thanks for letting me know :smile_cat:
