### ISSUE TITLE
Possibility of creating a dynamic linked library

### ISSUE THREAD

**Issue by epsilon-0** [uNetworking/uSockets#99]
To give an idea of my use case:  
I want to use `uWebSockets` in a small pastebin kind of program, and it mentions that `uSockets` is a dependency. I am currently a bit stuck on how to port this to Gentoo as a package for everyone to use.

(I am very new to C/C++ programming so forgive my stupid questions)

If I am understanding correctly the code is NOT just header files, I also need to add the `*.c` files while compiling.

Is it possible I am missing something? 
If I my previous hypothesis was not, is it very hard to change this to a headers only library like `uWebSockets` ?

**Comment by alexhultman** [comment]
Dynamic libraries are much slower, as small functions that normally get LTO-inlined is now forced to be dynamic actual calls:

alexhultman@clr-9c9c4beff725453db9688b589234d573~/uWebSockets.js/uWebSockets/uSockets $ ./http_load_test 40 127.0.0.1 3000
Running benchmark now...
Req/sec: 162503.750000
Req/sec: 162577.250000
Req/sec: 163431.000000
Req/sec: 162965.500000
Req/sec: 163177.250000
^C
alexhultman@clr-9c9c4beff725453db9688b589234d573~/uWebSockets.js/uWebSockets/uSockets $ ./http_load_test 40 127.0.0.1 3000
Running benchmark now...
Req/sec: 213122.000000
Req/sec: 214782.250000
Req/sec: 213757.750000
Req/sec: 215530.750000
^C

There's a 32% perf diff here between a dynamic and static compilation. This library is designed to be statically compiled - you can install that library.
